import type { Instrument } from '../types';

export const INSTRUMENTS: Instrument[] = [
  {
    id: 'guitar-6',
    name: '6-струнная гитара',
    category: 'guitars',
    description: 'Акустическая и электрогитара, стандартный строй E A D G B E',
    iconName: 'Guitar',
    stringCount: 6,
    headstockStyle: 'classic-3x3',
    activeTuningId: 'standard',
    tunings: [
      {
        id: 'standard',
        name: 'Стандартный (E A D G B E)',
        strings: [
          { id: 'g6-e2', name: 'E', octave: 2, fullName: 'E2', freq: 82.41, stringNumber: 6, pegSide: 'left', pegIndex: 0, thickness: 3.5 },
          { id: 'g6-a2', name: 'A', octave: 2, fullName: 'A2', freq: 110.00, stringNumber: 5, pegSide: 'left', pegIndex: 1, thickness: 3.0 },
          { id: 'g6-d3', name: 'D', octave: 3, fullName: 'D3', freq: 146.83, stringNumber: 4, pegSide: 'left', pegIndex: 2, thickness: 2.5 },
          { id: 'g6-g3', name: 'G', octave: 3, fullName: 'G3', freq: 196.00, stringNumber: 3, pegSide: 'right', pegIndex: 2, thickness: 2.0 },
          { id: 'g6-b3', name: 'B', octave: 3, fullName: 'B3', freq: 246.94, stringNumber: 2, pegSide: 'right', pegIndex: 1, thickness: 1.6 },
          { id: 'g6-e4', name: 'E', octave: 4, fullName: 'E4', freq: 329.63, stringNumber: 1, pegSide: 'right', pegIndex: 0, thickness: 1.2 },
        ],
      },
      {
        id: 'drop-d',
        name: 'Drop D (D A D G B E)',
        strings: [
          { id: 'g6-d2', name: 'D', octave: 2, fullName: 'D2', freq: 73.42, stringNumber: 6, pegSide: 'left', pegIndex: 0, thickness: 3.5 },
          { id: 'g6-a2', name: 'A', octave: 2, fullName: 'A2', freq: 110.00, stringNumber: 5, pegSide: 'left', pegIndex: 1, thickness: 3.0 },
          { id: 'g6-d3', name: 'D', octave: 3, fullName: 'D3', freq: 146.83, stringNumber: 4, pegSide: 'left', pegIndex: 2, thickness: 2.5 },
          { id: 'g6-g3', name: 'G', octave: 3, fullName: 'G3', freq: 196.00, stringNumber: 3, pegSide: 'right', pegIndex: 2, thickness: 2.0 },
          { id: 'g6-b3', name: 'B', octave: 3, fullName: 'B3', freq: 246.94, stringNumber: 2, pegSide: 'right', pegIndex: 1, thickness: 1.6 },
          { id: 'g6-e4', name: 'E', octave: 4, fullName: 'E4', freq: 329.63, stringNumber: 1, pegSide: 'right', pegIndex: 0, thickness: 1.2 },
        ],
      },
      {
        id: 'half-step-down',
        name: 'На полтона ниже (Eb Ab Db Gb Bb Eb)',
        strings: [
          { id: 'g6-eb2', name: 'D#', octave: 2, fullName: 'D#2', freq: 77.78, stringNumber: 6, pegSide: 'left', pegIndex: 0, thickness: 3.5 },
          { id: 'g6-ab2', name: 'G#', octave: 2, fullName: 'G#2', freq: 103.83, stringNumber: 5, pegSide: 'left', pegIndex: 1, thickness: 3.0 },
          { id: 'g6-db3', name: 'C#', octave: 3, fullName: 'C#3', freq: 138.59, stringNumber: 4, pegSide: 'left', pegIndex: 2, thickness: 2.5 },
          { id: 'g6-gb3', name: 'F#', octave: 3, fullName: 'F#3', freq: 185.00, stringNumber: 3, pegSide: 'right', pegIndex: 2, thickness: 2.0 },
          { id: 'g6-bb3', name: 'A#', octave: 3, fullName: 'A#3', freq: 233.08, stringNumber: 2, pegSide: 'right', pegIndex: 1, thickness: 1.6 },
          { id: 'g6-eb4', name: 'D#', octave: 4, fullName: 'D#4', freq: 311.13, stringNumber: 1, pegSide: 'right', pegIndex: 0, thickness: 1.2 },
        ],
      },
    ],
  },
  {
    id: 'bass-4',
    name: 'Бас-гитара (4 струны)',
    category: 'bass',
    description: 'Четырехструнный бас, строй E A D G',
    iconName: 'Disc',
    stringCount: 4,
    headstockStyle: 'bass-4',
    activeTuningId: 'standard-bass',
    tunings: [
      {
        id: 'standard-bass',
        name: 'Стандартный бас (E A D G)',
        strings: [
          { id: 'b4-e1', name: 'E', octave: 1, fullName: 'E1', freq: 41.20, stringNumber: 4, pegSide: 'left', pegIndex: 0, thickness: 4.2 },
          { id: 'b4-a1', name: 'A', octave: 1, fullName: 'A1', freq: 55.00, stringNumber: 3, pegSide: 'left', pegIndex: 1, thickness: 3.6 },
          { id: 'b4-d2', name: 'D', octave: 2, fullName: 'D2', freq: 73.42, stringNumber: 2, pegSide: 'right', pegIndex: 1, thickness: 3.0 },
          { id: 'b4-g2', name: 'G', octave: 2, fullName: 'G2', freq: 98.00, stringNumber: 1, pegSide: 'right', pegIndex: 0, thickness: 2.4 },
        ],
      },
    ],
  },
  {
    id: 'ukulele',
    name: 'Укулеле (Сопрано)',
    category: 'folk',
    description: 'Гавайская 4-струнная гитара, строй G C E A',
    iconName: 'Music',
    stringCount: 4,
    headstockStyle: 'ukulele-2x2',
    activeTuningId: 'standard-uke',
    tunings: [
      {
        id: 'standard-uke',
        name: 'Стандартный укулеле (G C E A)',
        strings: [
          { id: 'uk-g4', name: 'G', octave: 4, fullName: 'G4', freq: 392.00, stringNumber: 4, pegSide: 'left', pegIndex: 0, thickness: 2.2 },
          { id: 'uk-c4', name: 'C', octave: 4, fullName: 'C4', freq: 261.63, stringNumber: 3, pegSide: 'left', pegIndex: 1, thickness: 2.6 },
          { id: 'uk-e4', name: 'E', octave: 4, fullName: 'E4', freq: 329.63, stringNumber: 2, pegSide: 'right', pegIndex: 1, thickness: 2.0 },
          { id: 'uk-a4', name: 'A', octave: 4, fullName: 'A4', freq: 440.00, stringNumber: 1, pegSide: 'right', pegIndex: 0, thickness: 1.6 },
        ],
      },
    ],
  },
  {
    id: 'guitar-7',
    name: '7-струнная гитара',
    category: 'guitars',
    description: 'Семиструнная электрогитара с низкой си (B1 E2 A2 D3 G3 B3 E4)',
    iconName: 'Guitar',
    stringCount: 7,
    isStub: true,
    stubMessage: 'Добавление 7-й струны запланировано в следующем релизе. Архитектура готова к подключению.',
    headstockStyle: 'classic-3x3',
    activeTuningId: 'standard-7',
    tunings: [],
  },
  {
    id: 'guitar-12',
    name: '12-струнная гитара',
    category: 'guitars',
    description: 'Двенадцатиструнная гитара со сдвоенными струнами',
    iconName: 'Guitar',
    stringCount: 12,
    isStub: true,
    stubMessage: 'Модуль парных октавных струн в разработке.',
    headstockStyle: 'classic-3x3',
    activeTuningId: 'standard-12',
    tunings: [],
  },
  {
    id: 'violin',
    name: 'Скрипка',
    category: 'strings',
    description: 'Классическая скрипка, строй G D A E',
    iconName: 'Activity',
    stringCount: 4,
    isStub: true,
    stubMessage: 'Пресеты для смычковых инструментов появятся в скором обновлении.',
    headstockStyle: 'classic-3x3',
    activeTuningId: 'standard-violin',
    tunings: [],
  },
];
